# Default, Defaults
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

# Jekyll Defaults
title: reconnaiction
email: erwan.le.roux7@gmail.com
description: Personnal blog
baseurl: "" # the subpath of your site, e.g. /blog

# Where can people find your site?
# url: "http://localhost:6000"
# When developing, set this ^ equal to whatever localhost you're using

# Socail Media links
# Use these to link users to your organization's social media sites
twitter:
facebook:
google:

